# GitHub Pages Configuration
# This file tells GitHub Pages how to build your site

# Basic site information
title: "My Custom Website"
description: "A modern, responsive website"
author: "Your Name"

# IMPORTANT: Custom domain configuration
# Replace 'yourdomain.com' with your actual custom domain
# Uncomment the lines below and add your domain:
# url: "https://yourdomain.com"
# baseurl: ""

# Example for different domain types:
# For www subdomain: url: "https://www.yourdomain.com"
# For apex domain: url: "https://yourdomain.com"

# Build settings (keep these as they are)
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins for better functionality
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Files to exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore